### ISSUE TITLE
TypeError in version 3.2.0

### ISSUE THREAD

**Issue by YoannUniKS** [pyparsing/pyparsing#577] opened 2024-10-14 11:53 UTC
Hi, 

I just updated from 3.1.4 to 3.2.0 and I get the following error when the package is loaded, in pyparsing/util.py, line 17 `_all_names: list[str] = []`:

> TypeError: 'type' object is not subscriptable

I am using Python 3.8.19.

Thanks in advance for the feedback!

**Comment by elephaint** [comment] 2024-10-14 15:59
Also see this issue in our CI tests on Python 3.8, the fix should be simple, i.e.

```
from typing import List

_all_names: List[str] = []:
```

Python 3.8 does not support this use of `list[str]`, which is the cause of the issue.

**Comment by ptmcg** [comment] 2024-10-14 16:29
Pyparsing 3.2.0 does not support Python versions earlier than 3.9. This is captured in the pyproject.toml file, and described up top in the CHANGES document.

**Comment by elephaint** [comment] 2024-10-14 17:03
You're right! Didn't realize this yet. We'll just update our dependencies.

**Comment by ptmcg** [comment] 2024-10-14 17:37
I just created a Python3.8 environment, and then did "pip install matplotlib", and it correctly pulled in the older pyparsing version.

But to your general question, pyparsing 3.2.0 is going to be Python 3.9, and if an older version is required, people should use the older version.

Ideally, you would create an adaptive requirement that looks something like this (not tested):
```
pyparsing > "3.2";~="3.1";python_version<"3.9"
```

**Comment by BioTurboNick** [comment] 2024-10-14 21:00
Does conda ignore the pyproject.toml? Because my code broke today, hitting this issue, and I spent all afternoon trying to figure out why. Restricing to pyparsing 3.1 worked.

It's a dependency of a dependency, and I'm currently stuck on Python 3.8 for this package, so I have to make do.

But, glad this issue exists because now I know what happened.

**Comment by ptmcg** [comment] 2024-10-15 15:05
I found that using a requirements.txt with these entries installs the desired version of pyparsing:
```
matplotlib
pyparsing>=3.2;python_version>="3.9"
pyparsing>=3.1;python_version<"3.9"
```

**Comment by ptmcg** [comment] 2024-10-20 12:40
Closing as resolved.

**Closed by ptmcg** 2024-10-20 12:40 UTC
