### ISSUE TITLE
ParseResults.scanString is not recursive

### ISSUE THREAD

**Issue by EdwardJB** [pyparsing/pyparsing#125] opened 2019-09-18 11:56 UTC
I need to return matched text _and start/end offsets_ from my parser. I understand `scanString` is the way to return the offsets. But there's a bug where only the root level matches include that information. Any nested elements just contain `ParseResults` objects (and oddly they don't seem to contain offset information either).

**Comment by ptmcg** [comment] 2019-09-18 21:45
This is how `scanString` is designed, and is not a bug - looks like I need to do a better job documenting `scanString`. Still it is possible to get this kind of data for any `ParserElement` by wrapping it in `locatedExpr`, and you wouldn't even need to use `scanString` to use it:

    import pyparsing as pp
    
    wd = pp.Word(pp.alphas)
    num = pp.Word(pp.nums)
    
    parser = (wd | num)[...]
    
    print(parser.parseString("AAA BBB 329847 DEF").dump())

Prints:

    ['AAA', 'BBB', '329847', 'DEF']

But if I change to:

    wd = pp.locatedExpr(pp.Word(pp.alphas))
    num = pp.locatedExpr(pp.Word(pp.nums))

We get:

```
[[0, 'AAA', 3], [4, 'BBB', 7], [8, '329847', 14], [15, 'DEF', 18]]
[0]:
  [0, 'AAA', 3]
  - locn_end: 3
  - locn_start: 0
  - value: 'AAA'
[1]:
  [4, 'BBB', 7]
  - locn_end: 7
  - locn_start: 4
  - value: 'BBB'
[2]:
  [8, '329847', 14]
  - locn_end: 14
  - locn_start: 8
  - value: '329847'
[3]:
  [15, 'DEF', 18]
  - locn_end: 18
  - locn_start: 15
  - value: 'DEF'

```

**Comment by EdwardJB** [comment] 2019-09-19 13:36
Thanks a lot for the detailed reply!

I tried the `locatedExpr` method but the behaviour seems the same as with `scanString`: Only the root level results include offset information (via the `locn_start` and `locn_end` properties). But for any nested results, that information is missing.

To use your example to demonstate:

```
import pyparsing as pp

wd = pp.Word(pp.alphas)
num = pp.Word(pp.nums)

parser = pp.locatedExpr((wd | num)[...])

print(parser.parseString("AAA BBB 329847 DEF").dump())
```

```[[0, 'AAA', 'BBB', '329847', 'DEF', 18]]
[0]:
  [0, 'AAA', 'BBB', '329847', 'DEF', 18]
  - locn_end: 18
  - locn_start: 0
  - value: ['AAA', 'BBB', '329847', 'DEF']
```

Now offsets for `wd` and `num` are missing.

In principle I could explicitly wrap every element of my grammar definition in `locatedExp`, but given my case in quite complex that would make development a lot less enjoyable. Is there any way to make all expressions `locatedExp`s by default? Come to think of it, is there any reason `pyparsing` doesn't to return offset information by default? It seems quite a basic need.

**Comment by ptmcg** [comment] 2019-09-19 21:21
Yes, that is pretty much consistent with my previous post. Can you describe your application a little more, and how your parser will use these start/end values? Pyparsing doesn't automatically create these because many parsers are built up from many small bits, and adding the extra structure for every piece makes the parsed data *more* difficult to work with. Maybe you are trying to duplicate some behavior that pyparsing already does for you (like replacing some matched content with some other generated content). I understand if you can't post your entire parser, but perhaps you could post a simple example showing how you will use the start/end locations.

**Comment by ptmcg** [comment] 2019-09-27 09:39
@EdwardJB - could you post a small snippet showing how you would use these start/end locations?

**Comment by EdwardJB** [comment] 2019-09-27 16:40
Hi Paul,

Thanks for your feedback. It's not so much that the locations are using during _interpretation_ of the text, but more that I need the spans for later use. Part of my usecase is returning offsets so they can be used to highlight terms in a subsequent NER annotation task (with [Prodigy](https://prodi.gy/)).

When I first filed this bug I had just started with `pp`. I've actually developed Python-based parsers myself in the past (though not open source sadly) - but ones that used a Regular Expression engine to do the actual matching. So adapting to structured matches took a bit of work. And not having offset information "out-of-the-box" like with regex was a bit disconcerting. Even so, having worked with `pp` for the last week, I've basically achieved what I want: parsing plain text into hierarchical yaml, with the structure following that of the grammar, with offset information for all elements.

Having said that, I still feel that location information is effectively _metadata_, and treating it like the _semantics_ of the text  (i.e. by running it through the `parseAction` functions) is strange. I would have expected a (possibly hidden) `ParseResults.metadata` field containing general match information like offsets. But perhaps your use cases just never require it?

I also live and die by visual representations of my parsers (i.e. syntax diagrams) as that's just how my brain works. I implemented these sorts of things into my previous projects. Are you aware of any way of diagramming `pp`? If not, would you be open to a PR?

**Comment by ptmcg** [comment] 2019-10-20 14:25
I have tried to make the repr strings for parser elements to be visual cues about how the parser actually works. It's okay for short expressions, but in practice this quickly breaks down, and the strings for complete parsers get to be long and unhelpful.

A syntax diagram generator for pyparsing parsers would be very cool. Are you thinking this would require changes to the pyparsing classes themselves? I think Python's introspection capabilities would be sufficient for an external tool to be able to create these, and you could use the internal `expr` and `exprs` attributes of `ParseElementEnhance` and `ParseExpression` respectively to navigate the parser structure. Perhaps something that would create an intermediate format, like EBNF, and then visualize with this utility I just found, https://bottlecaps.de/rr/ui.

**Comment by EdwardJB** [comment] 2019-10-21 08:34
Those are decent ideas.

When I did this previously, I used a syntax diagram generator (I think this one: https://github.com/tabatkins/railroad-diagrams).

The approach was pretty simple. Each parser element (except `Literal`) gets a method that returns its children wrapped in its equivalent diagram object. So for `Or`:

```python
...
def visualise(self):
    exprs=[expr.visualise() for expr in exprs]
    return diagrams.Choice(exprs)
...
```

Besides peripheral questions about how to pop up diagrams (e.g. in a browser), saving PNGs, showing inline in Jupyter, etc., that's kinda all she wrote.

**Comment by ptmcg** [comment] 2019-11-11 12:50
I think this could be done using an external Visitor that walks a pyparsing parser's structure and emits diagrams element instances.  I'll try to look at this this week.

**Comment by ptmcg** [comment] 2020-07-10 19:22
The latest 3.0.0a2 pre-release includes support for generating railroad diagrams - check it out!

**Comment by EdwardJB** [comment] 2020-07-10 19:27
Very cool! I'll take a look.

**Comment by ptmcg** [comment] 2021-09-09 02:41
Huge upgrade in the pyparsing railroad-diagrams in latest 3.0.0rc1 release! I'm really liking the results, plus the option to annotate with any attached results names.

For now, I'm closing this issue. If you have additional questions about locatedExpr (which has been superseded by the Located class in 3.0.0), you can reopen or start a new issue - but please include some more specifics about what you are doing with it.

**Closed by ptmcg** 2021-09-09 02:41 UTC
