### ISSUE TITLE
DeprecationWarning: distutils

### ISSUE THREAD

**Issue by jameszhang-a** [pyparsing/pyparsing#377] opened 2022-03-24 23:35 UTC
Got this warning message:

```
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. 
Use setuptools or check PEP 632 for potential alternatives
  from distutils.errors import PreprocessError
```

**Comment by ptmcg** [comment] 2022-03-25 00:15
What version of pyparsing?
Under what conditions were you getting this warning?

It is very likely that as of the next release this will have been resolved, since setup.py is being replaced with pyproject.toml to define the build and test environments.

**Comment by ptmcg** [comment] 2022-04-10 06:23
Can you reproduce this issue with the latest 3.0.8 release?

**Comment by ptmcg** [comment] 2022-07-12 00:14
Closing - reopen if there is any supporting information to report.

**Closed by ptmcg** 2022-07-12 00:14 UTC
