### ISSUE TITLE
QuotedString doesn't support multiple escape sequences

### ISSUE THREAD

**Issue by nadavhaik** [pyparsing/pyparsing#572] opened 2024-09-25 08:05 UTC
The QuotedString class supports only a single optional esc_quote parameter.
This prevents implementing modern SQL string syntaxes, such as Snowflake, that supports both a double apostrophe ('') and backslash+single apostrophe (\') as escape sequences.
I tried using workarounds like passing a unified regex as esc_quote (r"('')|(\')"), or passing esc_quote="''",esc_char=r"\", but neither of them worked.
I ended up implementing my own QuotedString, which could be slightly adjusted and implemented natively in pyparsing with backwards compatibility:
```
class FixedQuotedString(Token):
    """
    This is an extension of pyparsing's QuotedString, that supports multiple escape quotes for the same string.
    This extension does that by overriding QuotedString's constructor and parseImpl.
    """

    ws_map = ((r"\t", "\t"), (r"\n", "\n"), (r"\f", "\f"), (r"\r", "\r"))

    def __init__(
        self,
        quote_char: str = "",
        esc_char: str | None = None,
        esc_quotes: str | typing.Sequence[str] = (),
        multiline: bool = False,
        unquote_results: bool = True,
        end_quote_char: str | None = None,
        convert_whitespace_escapes: bool = True,
        *,
        quoteChar: str = "",
        escChar: str | None = None,
        escQuotes: str | typing.Sequence[str] = (),
        unquoteResults: bool = True,
        endQuoteChar: str | None = None,
        convertWhitespaceEscapes: bool = True,
    ):

        super().__init__()

        escChar = escChar or esc_char

        escQuotes = escQuotes or esc_quotes
        esc_quotes_fixed: typing.Sequence[str] = (
            (escQuotes,) if isinstance(escQuotes, str) else escQuotes
        )

        unquoteResults = unquoteResults and unquote_results
        endQuoteChar = endQuoteChar or end_quote_char
        convertWhitespaceEscapes = (
            convertWhitespaceEscapes and convert_whitespace_escapes
        )
        quote_char = quoteChar or quote_char

        # remove white space from quote chars - wont work anyway
        quote_char = quote_char.strip()
        if not quote_char:
            raise ValueError("quote_char cannot be the empty string")

        if endQuoteChar is None:
            endQuoteChar = quote_char
        else:
            endQuoteChar = endQuoteChar.strip()
            if not endQuoteChar:
                raise ValueError("endQuoteChar cannot be the empty string")

        self.quoteChar = quote_char
        self.quoteCharLen = len(quote_char)
        self.firstQuoteChar = quote_char[0]
        self.endQuoteChar = endQuoteChar
        self.endQuoteCharLen = len(endQuoteChar)
        self.escChar = escChar
        self.esc_quotes_fixed = esc_quotes_fixed
        self.unquoteResults = unquoteResults
        self.convertWhitespaceEscapes = convertWhitespaceEscapes

        sep = ""
        inner_pattern = ""

        for esq_quote in esc_quotes_fixed:
            inner_pattern += r"{}(?:{})".format(sep, re.escape(esq_quote))
            sep = "|"

        if escChar:
            inner_pattern += r"{}(?:{}.)".format(sep, re.escape(escChar))
            sep = "|"
            self.escCharReplacePattern = re.escape(self.escChar) + "(.)"

        if len(self.endQuoteChar) > 1:
            inner_pattern += (
                "{}(?:".format(sep)
                + "|".join(
                    "(?:{}(?!{}))".format(
                        re.escape(self.endQuoteChar[:i]),
                        re.escape(self.endQuoteChar[i:]),
                    )
                    for i in range(len(self.endQuoteChar) - 1, 0, -1)
                )
                + ")"
            )
            sep = "|"

        if multiline:
            self.flags = re.MULTILINE | re.DOTALL
            inner_pattern += r"{}(?:[^{}{}])".format(
                sep,
                FixedQuotedString._escape_regex_range_chars(self.endQuoteChar[0]),
                (
                    FixedQuotedString._escape_regex_range_chars(escChar)
                    if escChar is not None
                    else ""
                ),
            )
        else:
            self.flags = 0
            inner_pattern += r"{}(?:[^{}\n\r{}])".format(
                sep,
                FixedQuotedString._escape_regex_range_chars(self.endQuoteChar[0]),
                (
                    FixedQuotedString._escape_regex_range_chars(escChar)
                    if escChar is not None
                    else ""
                ),
            )

        self.pattern = "".join(
            [
                re.escape(self.quoteChar),
                "(?:",
                inner_pattern,
                ")*",
                re.escape(self.endQuoteChar),
            ],
        )

        try:
            self.re = re.compile(self.pattern, self.flags)
            self.reString = self.pattern
            self.re_match = self.re.match
        except re.error:
            raise ValueError(
                "invalid pattern {!r} passed to Regex".format(self.pattern),
            )

        self.errmsg = "Expected " + self.name
        self.mayIndexError = False
        self.mayReturnEmpty = True

    def parseImpl(self, instring: str, loc: int, doActions=True):
        result = (
            instring[loc] == self.firstQuoteChar
            and self.re_match(instring, loc)
            or None
        )
        if not result:
            raise ParseException(instring, loc, self.errmsg, self)

        loc = result.end()
        ret = result.group()

        if self.unquoteResults:

            # strip off quotes
            ret = ret[self.quoteCharLen : -self.endQuoteCharLen]

            if isinstance(ret, str_type):
                # replace escaped whitespace
                if "\\" in ret and self.convertWhitespaceEscapes:
                    for wslit, wschar in self.ws_map:
                        ret = ret.replace(wslit, wschar)

                # replace escaped characters
                if self.escChar:
                    ret = re.sub(self.escCharReplacePattern, r"\g<1>", ret)

                # replace escaped quotes
                for esq_quote in self.esc_quotes_fixed:
                    ret = ret.replace(esq_quote, self.endQuoteChar)

        return loc, ret

    @staticmethod
    def _escape_regex_range_chars(s: str) -> str:
        # escape these chars: ^-[]
        for c in r"\^-[]":
            s = s.replace(c, _BSLASH + c)
        s = s.replace("\n", r"\n")
        s = s.replace("\t", r"\t")
        return str(s)
   ```

**Comment by ptmcg** [comment] 2024-09-25 14:41
Here is a test string from the [Snowflake docs](https://docs.snowflake.com/en/sql-reference/data-types-text), modified to add a `\'` escaped single quote, and how I parsed it using the `QuotedString` class (defined both `esc_quote` and `esc_char` parameters):

```
>>> test = r"'Today''s sales projections', '-'''' \'-'"
>>> print(test)
'Today''s sales projections', '-'''' \'-'
>>> pp.DelimitedList(pp.QuotedString("'", esc_quote="''", esc_char="\\")).parse_string(test, parse_all=True).as_list()
["Today's sales projections", "-'' '-"]```
```

In the second element of the returned list, we see the `\'` has been converted to a single `'`, So I think adding `esc_char="\\"` will do the minimum you have asked about.

I _do_ see that the Snowflake docs also describe using "\" for control characters ("\n", "\t", etc.) and octal, hex, and Unicode sequences. `QuotedString` handles the whitespace escapes like `\t`, but not the octal, hex, and Unicode ones. That would be a nice feature to add.

**Comment by nadavhaik** [comment] 2024-10-01 12:34
@ptmcg
hi, you could try parsing `"'Today''s sales\' projections'"` .
it didn't work for me with your workaround, and I ended up implementing the FixedQuotedString class I provided as a workaround.

**Comment by ptmcg** [comment] 2024-10-01 13:18
Here is my Python session:

```python
>>> import pyparsing as pp
>>> pp.__version__                                                     
'3.2.0'
>>> qs = pp.QuotedString("'", esc_quote="''", esc_char="\\")
>>> qs.parse_string(r"'Today''s sales\' projections'", parse_all=True) 
ParseResults(["Today's sales' projections"], {})
```

I was testing this for a while until I realized I forgot the `r` to make the test string a raw string - is that what is happening for you?
```python
>>> qs.parse_string("'Today''s sales\' projections'", parse_all=True)  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ptmcg\dev\pyparsing\gh\pyparsing\pyparsing\core.py", line 1197, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found 'projections'  (at char 17), (line:1, col:18)
```

**Comment by ptmcg** [comment] 2024-10-01 15:41
Ok, then - I don't know what else to suggest. I'm unable to reproduce the problem with releases 3.2.0, 3.1.4, and 3.1.0.

Can you post the full set of statements you used to recreate your problem, like I did above?

**Comment by ptmcg** [comment] 2024-10-13 16:28
Closing. If you can reproduce the issue with the latest 3.2.0 pyparsing release, following the notes above, please reopen this issue, including the sample code (with input string and parser definition) that reproduces the problem.

**Closed by ptmcg** 2024-10-13 16:28 UTC
