### ISSUE TITLE
2.3.1 not backward compatible to 2.3.0

### ISSUE THREAD

**Issue by kochelmonster** [pyparsing/pyparsing#69] opened 2019-01-20 10:54 UTC
Please try out the attached test file. It runs in 2.3.0 but causes errors in 2.3.1.
[pyparsing_error.py.gz](https://github.com/pyparsing/pyparsing/files/2776484/pyparsing_error.py.gz)

**Comment by ptmcg** [comment] 2019-01-20 12:37
Thanks for posting. Looking into this, I suspect the cause is as mentioned in the opening bullet in the 2.3.1 CHANGES file, but it is difficult to wade through this complex example. When I dump() out  the parsed `result` variable, I get the same output for both 2.3.0 and 2.3.1, but the value passed to your build_quoted method is `['dog']` in 2.3.0 and `[['dog']]` in 2.3.1. It may also be related to the way that you build up the results structure in your parse actions, which gives me some ideas on where to look next.

**Comment by ptmcg** [comment] 2019-01-20 16:11
There are a *lot* of internal Group expressions in this parser, and I'm wondering if you had to put these there to work around the bug that was fixed. Also, I think you will get better results if you `.suppress()` the opening `Literal('/')` in `modifier_list`. Whenever I see dict keys that are punctuation, it leads me to believe something should be suppressed. Lastly, I'm pretty sure you have a bug when matching an escaped character in `Word("\\", metas, exact=1)`, should be `exact=2`. These won't fix your underlying problem, but I'm beginning to think that the fixed bug is entrenched deep in your parser and `build_xxx` design, and is not going to be a simple fix. l may have to re-release this as 2.4.0, so that people are more aware of the possible version incompatibilities. (Is there a chance you could produce a more compact demonstration of this problem?)

**Comment by kochelmonster** [comment] 2019-01-20 17:03
I am sorry that, the example is pretty complex. With some further investigation, I found a bug in the example, that brought me one step further to another error. Please try out the new test file.
I inserted a print statement in line 672.
while 2.3.0 correctly prints "simpleid" 2.3.1 prints "identifier"
[pyparsing_error.py.gz](https://github.com/pyparsing/pyparsing/files/2776681/pyparsing_error.py.gz)

**Comment by ptmcg** [comment] 2019-01-21 11:59
Looking further into this later today

**Comment by admix** [comment] 2019-01-22 22:52
Confirming that this is indeed the case and moreover, `sqlalchemy-searchable` relying on this library and with 2.3.1 upgrade - all the search related functionality started to fail. Not quite sure where exactly sqlalchemy is using it tho.

**Comment by ptmcg** [comment] 2019-01-23 01:52
I can't find any `sqlalchemy-searchable` repos that use pyparsing. There is one that refers to it, but their reference is that they removed it from their requirements.txt last summer. Can you post some links or issues that describe the failing search functionality?

**Comment by mueslo** [comment] 2019-02-11 14:40
I'm running into the same issue. 2.3.1 is definitely not backwards-compatible to 2.3.0. I have a more compact example (albeit still rather complex).

https://gist.github.com/mueslo/4813f0d67fc596c96714dd82495c7608

**Comment by ptmcg** [comment] 2019-02-12 03:33
Thanks for this post, it is much closer to an MCVE for me to work with. I am now thinking how to address this. Several steps need to happen: pull release 2.3.1 and re-release 2.4.0 for those using and relying on the fixed behavior; release 2.3.2 with the other changes in 2.3.1 not related this bugfix; add a mechanism to 2.3.2 for users who are depending on the current behavior to roll forward to 2.4.x without additional code changes (I am considering a class that can be added to And instances that will do Group behavior in 2.3.x and no-op behavior in 2.4.0 and later - this would be a transitional feature that would be dropped in 2.5 or 2.6 release, but would make it easier for people who currently rely on the bug behavior to fix their code in 2.3.x realm, upgrade to 2.4.x, then remove the no-op classes before upgrading further.) Or is this change so radical that it should be a 3.0 release? Comments invited.

**Comment by ptmcg** [comment] 2019-02-12 03:58
Another compatibility option might be similar to Python's `from __future__ import xxx`, which changes behavior for the current module. This might take the form of a separate import that would locally apply the bug fix, or a context manager that defines a narrow scope for adding the new behavior. In either case, the features would become no-ops after upgrading to the release where the bugfix is the normal behavior.

**Comment by mueslo** [comment] 2019-02-12 08:08
Thanks for the swift reply. I can't speak for others, but I personally had
specified my pyparsing dep as "pyparsing~=2.2", which would have also
broken on a 2.4 api change. However, I think since overall it's not a major
change it should be fine for a 2.4 release (and I really should have been
using ~=2.2.x to avoid unexpected breakage), as long as it's sufficiently
announced (i.e. warn about this wherever possible). A 3.0 release with this
change would of course be safer, and should not break for anyone using sane
version constraints, but that's up to your judgement and version style
preference.

Am Di., 12. Feb. 2019, 04:58 hat Paul McGuire <notifications@github.com>
geschrieben:

**Comment by ptmcg** [comment] 2019-03-30 05:58
Ok, I think I have finally come to a resolution on this. I will push out a release 2.4.0 that contains the new behavior by default, but like Python's `__future__`, there will be a `pyparsing.__compat__` namespace, containing the switch `pyparsing.__compat__.collect_all_And_tokens`. This value will be True by default, reflecting the post-bugfix behavior in 2.3.1.  User code can set the value to False to restore the pre-bugfix behavior. This switch and the conditional code will be retained through the 2.4.x versions. Beyond 2.4.x, the conditional code will be removed, and setting the switch will have no effect.

I was considering doing a 2.3.2 and 2.4.0 releases with and without the bugfix, and tracking 2.3.x and 2.4.x releases, but I think this approach will be simpler.

**Comment by ptmcg** [comment] 2019-03-30 08:22
Please pull this latest version and see if the `__compat__` setting will work for you.

**Comment by ptmcg** [comment] 2019-04-08 04:47
Version 2.4.0 released with `__compat__` switch, restoring pre-bugfix behavior.

**Closed by ptmcg** 2019-04-08 04:47 UTC
