### ISSUE TITLE
pyparsing fails to import after pip install pyparsing

### ISSUE THREAD

**Issue by pingdink** [pyparsing/pyparsing#243] opened 2020-09-10 18:28 UTC
![Screen Shot 2020-09-10 at 12 15 39 PM](https://user-images.githubusercontent.com/9258889/92779599-6cbd2800-f35f-11ea-90a4-5eeff84d125a.png)

**Comment by ptmcg** [comment] 2020-09-10 18:44
Duplicate of #242

**Closed by ptmcg** 2020-09-10 18:44 UTC
