### ISSUE TITLE
single character Word not getting captured when directly adjacent to a Literal in pp 3.0.0

### ISSUE THREAD

**Issue by rjdbcm** [pyparsing/pyparsing#313] opened 2021-10-23 20:51 UTC
```
x = Literal("<@>")
id = Word(alphas + '_', alphanums + '_')
loop = id + x + id
loop.parse_string('a<@>b2')
```
This will cause an error for me.

Here I have the diff for parse_string and my vendored PP 2.4.3 parseString:

<img width="1419" alt="Screen Shot 2021-10-23 at 3 39 48 PM" src="https://user-images.githubusercontent.com/42073607/138570971-5679b7da-73d8-4b6e-81b4-30e59b53a948.png">

The version is 3.10.0 for Python and here is the error I get:

```

self = {{Forward: {Group:({Group:({[{Combine:({'#' cython.binding | cython.boundscheck | cython.wraparound | cython.initializ...(A-Za-z)} '='} {Forward: None | {{{{{{{{{{{{Forward: None | Forward: operator term} | Combine:(Forward: bitwise o}...]}
instring = '`first-class functions`\n(Add(x = 3 -> int; y = 3 -> int)) int\n        <*>x+y\n\n`generators`\n(Yield123()) coroutin...1 % denom\ndiv_by_zero2 = 1 / 0\nmod_zero2 = 1 % 0\ntruth = 1 + 1 == 2 >> 0\n\nmain:\nHello()\nprint("I\'m a binary.")'
parse_all = False

    def parse_string(
        self, instring: str, parse_all: bool = False, *, parseAll: bool = False
    ) -> ParseResults:
        """
        Parse a string with respect to the parser definition. This function is intended as the primary interface to the
        client code.
    
        :param instring: The input string to be parsed.
        :param parse_all: If set, the entire input string must match the grammar.
        :param parseAll: retained for pre-PEP8 compatibility, will be removed in a future release.
        :raises ParseException: Raised if ``parse_all`` is set and the input string does not match the whole grammar.
        :returns: the parsed data as a :class:`ParseResults` object, which may be accessed as a `list`, a `dict`, or
          an object with attributes if the given parser includes results names.
    
        If the input string is required to match the entire grammar, ``parse_all`` flag must be set to ``True``. This
        is also equivalent to ending the grammar with :class:`StringEnd`().
    
        To report proper column numbers, ``parse_string`` operates on a copy of the input string where all tabs are
        converted to spaces (8 spaces per tab, as per the default in ``string.expandtabs``). If the input string
        contains tabs and the grammar uses parse actions that use the ``loc`` argument to index into the string
        being parsed, one can ensure a consistent view of the input string by doing one of the following:
    
        - calling ``parse_with_tabs`` on your grammar before calling ``parse_string`` (see :class:`parse_with_tabs`),
        - define your parse action using the full ``(s,loc,toks)`` signature, and reference the input string using the
          parse action's ``s`` argument, or
        - explicitly expand the tabs in your input string before calling ``parse_string``.
    
        Examples:
    
        By default, partial matches are OK.
    
        >>> res = Word('a').parse_string('aaaaabaaa')
        >>> print(res)
        ['aaaaa']
    
        The parsing behavior varies by the inheriting class of this abstract class. Please refer to the children
        directly to see more examples.
    
        It raises an exception if parse_all flag is set and instring does not match the whole grammar.
    
        >>> res = Word('a').parse_string('aaaaabaaa', parse_all=True)
        Traceback (most recent call last):
        ...
        pyparsing.ParseException: Expected end of text, found 'b'  (at char 5), (line:1, col:6)
        """
        parseAll = parse_all or parseAll
    
        ParserElement.reset_cache()
        if not self.streamlined:
            self.streamline()
        for e in self.ignoreExprs:
            e.streamline()
        if not self.keepTabs:
            instring = instring.expandtabs()
        try:
            loc, tokens = self._parse(instring, 0)
            if parseAll:
                loc = self.preParse(instring, loc)
                se = Empty() + StringEnd()
                se._parse(instring, loc)
        except ParseBaseException as exc:
            if ParserElement.verbose_stacktrace:
                raise
            else:
                # catch and re-raise exception from here, clearing out pyparsing internal stack trace
>               raise exc.with_traceback(None)
E               pyparsing.exceptions.ParseException: Expected end of text, found 'i'  (at char 520), (line:27, col:1)

../../.pyenv/versions/3.10.0/lib/python3.10/site-packages/pyparsing/core.py:1101: ParseException

```

I reran the code totally isolated and did not find the error. It appears to be coming from an IndentedBlock on the next line that has the literal as '(!)' rather than '<!>'.

**Comment by ptmcg** [comment] 2021-10-24 00:07
This isn't the actual exception that you got was it? It shouldn't list out the whole methods source code like that.

**Comment by rjdbcm** [comment] 2021-10-24 00:42
> Ah, my old nemesis, IndentedBlock. Yes, looking forward to seeing a repro example. (Or direct me to your source repo.)

Oh that was my pytest run output sorry about that. Though I have never seen it pull down the doc and source like that either. My source repo is rjdbcm/Aspidites.

**Comment by ptmcg** [comment] 2021-11-02 09:27
Please retest with latest release 3.0.4. After looking more closely at the other bug, it looks like it is something that I can't change easily, not without a 3.1 release I think.

Let me know how your testing goes.

**Comment by ptmcg** [comment] 2021-11-13 09:59
Please retest with latest 3.0.6 code, and verify if the issue is resolved, either with your custom IndentedBlock, or with the one provided in pyparsing 3.0.

**Comment by ptmcg** [comment] 2022-01-22 16:19
Is this still an open issue for you?

There was another bugfix in IndentedBlock, but I don't think the error it was fixing was the same as yours. In any event, could you retest with the new IndentedBlock?

**Comment by ptmcg** [comment] 2022-04-10 06:26
Closing as there has been no reply from submitter for 6 months. Please reopen if/when you have new notes on this issue.

**Closed by ptmcg** 2022-04-10 06:26 UTC
