### ISSUE TITLE
pyparsing library over flow when it exceed in max 18 condition?

### ISSUE THREAD

**Issue by Hemun143** [pyparsing/pyparsing#489] opened 2023-06-28 19:55 UTC
```
class BoolCustomAnd(BoolBinOp):
    pass


class BoolCustomOr(BoolBinOp):
    pass


class BoolCustomNot:
    pass

async def test_more_than_20_filters_with_pure_pyparsing():
    infix_not = infixNotation(
        Word(alphas, max=1),
        [
            (Keyword("not"), 1, opAssoc.RIGHT, BoolCustomNot),
            (Keyword("and"), 2, opAssoc.LEFT, BoolCustomAnd),
            (Keyword("or"), 2, opAssoc.LEFT, BoolCustomOr),
        ],
    ).setName("boolean_expression")

    pass_expression = f"((((((((((((((((((a) and b) and c) and d) and e) and f) and g) and h ) and i ) and j) and k) and l) and m) and n) and o) and p) and q) and r)"

    parsed_expr = infix_not.parseString(pass_expression)[0]
    print(parsed_expr)
```

> There is test use case of 18 condition where I have checked with expression and this is showing error like [maximum recursion depth exceeded while calling a Python]

```
    fail_expression = f"(((((((((((((((((((a) and b) and c) and d) and e) and f) and g) and h ) and i ) and j) and k) and l) and m) and n) and o) and p) and q) and r) and s)"
    with pytest.raises(RecursionError):
        print("Ran this")
        parsed_expr = infix_not.parseString(fail_expression)[0]

    print("reached here")
```

> I have check with 3.1.0 with my upgrade. But same issue persist.

**Comment by ptmcg** [comment] 2023-06-28 21:14
Python's recursion is set to an arbitrary level of 1000. Because pyparsing makes heavy use of the program stack, it is possible for some complex parsers, or for parsers that must handle deeply nested data, to exceed that number. There is nothing magic about the number 1000, the more important thing is that there _is_ a limit, to help Python stay running in the face of runaway recursion.

In your case, the recursion isn't really runaway, just deeper than usual. The parser isn't terribly complex, but you're input expression's nested parentheses consume the stack beyond the 1000 limit. There are some other examples in the Pyparsing examples directory that bump the recursion limit to 2000 or 3000, so you may need to do the same here, if this level of nesting is something you'll need to support.

As a side note, since you are using the `infix_notation` method, you might find a performance boost if you enable packrat parsing, by adding this method call just after importing pyparsing:

```python
pyparsing.ParserElement.enable_packrat()
```

This will turn on an internal memoizing cache which `infix_notation` can especially take advantage of.

**Comment by Hemun143** [comment] 2023-07-12 19:19
I am using with the same in my code, as I have some feature for go to the condition limit. So let me know if you have best way to per form the a-z condition as mention above.

**Comment by ptmcg** [comment] 2023-07-12 21:53
As I mentioned in my post, the first step you should try is to call `enable_packrat()`.  If you are still having issues, then try calling `sys.setrecursionlimit()` with 2000, then 3000 and so on - some parsers and some input strings just need a deeper call stack. (Note that eventually, you may set the recursion limit too high, which will cause Python to crash with a MemoryError. That is why I suggest increasing it a bit at a time, rather than just setting it to 100,000 or something.)

**Comment by ptmcg** [comment] 2023-07-29 18:08
Any further questions on this? If not, I'll close it for now - you can always reopen with followup comments.

**Comment by RobinetDenisAcsone** [comment] 2023-08-24 10:35
I have the same kind of problem, but in another situation (I can create another issue if you want)

In my case, it's the usage of the Forward expression, for things like a function that can have functions in argument.

As soon as the syntax is more complex, the depth can be highly impacted, in the minimal script attached, adding a `ZeroOrMore` make the max number of nested function goes from 141 to 82.
The real syntax have the limit at +- 30 nested function.

I tried with the `enable_packrat`, but the result is worse when enabled. (see the minimal script attached)
The `setrecursionlimit` isn't an option, while it works on Linux, on Windows the limit set by python is really close to the OS one.

Minimal script to reproduce: [recursionError.zip](https://github.com/pyparsing/pyparsing/files/12428383/recursionError.zip)

**Comment by ptmcg** [comment] 2023-08-28 07:57
@RobinetDenisAcsone I downloaded your script and I see your issue. I'm not sure, short of a massive rewrite of pyparsing's parsing implementation, that there is much I can do to eliminate this nesting. (I would have to replace Python's stack-based exception handling with my own recursive traversal of the grammar, and propagation of exceptions up that traversal code.)

I created these two railroad diagrams to reflect the minimal example's parsers. 
![image](https://github.com/pyparsing/pyparsing/assets/383875/1a1173d7-255d-4d6b-a4fb-b32a9c47b4da)

Your mention of your real syntax failing at ~30 nested functions sounds like we might be able to do some streamlining of your parser. If you can post the parser portion of your syntax, go ahead and open another issue with that and I can see if there is anywhere we can collapse out some nesting

**Comment by RobinetDenisAcsone** [comment] 2023-08-28 09:43
@ptmcg Thanks for the look, I will create another issue for that, it's an open source project, so I can link the code to you, but it's quite a big chunk of code.

**Comment by ptmcg** [comment] 2023-10-02 04:06
Closing this for now - supporting deeper recursion by moving the expression eval stack off of the Python program stack is an extensive project.

**Closed by ptmcg** 2023-10-02 04:06 UTC
