### ISSUE TITLE
Please revert changes that lead downstream projects to add extra spaces

### ISSUE THREAD

**Issue by glensc** [pyparsing/pyparsing#453] opened 2022-11-30 13:52 UTC
downstream projects like [pipenv](https://github.com/pypa/pipenv/issues/5506) are now forced to feed extra spaces:

```diff
-charset-normalizer==2.1.1; python_full_version >= '3.6.0'
+charset-normalizer==2.1.1 ; python_full_version >= '3.6.0'
```

refs:
- https://github.com/pypa/pipenv/issues/5506
- https://github.com/pypa/pipenv/issues/5506#issuecomment-1332138018
- https://github.com/sarugaku/requirementslib/commit/422cdae898f8b09aca9264daf803dfcc57d58549

**Comment by ptmcg** [comment] 2022-12-22 14:32
I will do my best, but I need more to work with. Where is the parser that parses these strings? Which version of pyparsing caused this regression? If you could supply a minimal reproducible example, I'll be happy to add it to pyparsing's test suite.

**Comment by glensc** [comment] 2022-12-22 14:55
actually, that doesn't create the markers, I don't know what triggers the creation of the markers like `python_full_version >= '3.6.0'`

**Comment by ferdnyc** [comment] 2024-12-06 01:00
@ptmcg This can probably be closed — it was a requirementslib issue that may or may not have been caused by pyparsing (it was never concretely determined), but pipenv no longer uses requirementslib. (see https://github.com/pypa/pipenv/issues/5506#issuecomment-1694169897)

**Comment by ptmcg** [comment] 2024-12-06 06:38
@ferdnyc Thanks for the update, the link from pipenv to pyparsing was missing. 

I just now took a look at requirementslib, and it doesn't use pyparsing either (I suspect it may have in the past, as there is a vestigial import of cached_property from a vendored version of pyparsing still there.)

If there was some regression in pyparsing behavior, either in requirementslib or pipenv, I never heard a word about it.

I'll close this since it seems to be moot at this point.

**Comment by ptmcg** [comment] 2024-12-06 06:39
Overtaken by events

**Closed by ptmcg** 2024-12-06 06:39 UTC
